### ISSUE TITLE
最近在用这个，可以检测IDE在线时间，使用语言种类,有感兴趣的看看，网址见describles

### ISSUE THREAD

**Issue by Aisuko** [G-Club/G-Club-Master#1]
https://wakatime.com

**Comment by falconhell** [comment]
安啦 



falconhell@163.com
 
发件人： Atsukon Lee
发送时间： 2017-03-06 20:29
收件人： G-Club/G-Club-Master
抄送： falconhell; Mention
主题： Re: [G-Club/G-Club-Master] 最近在用这个，可以检测IDE在线时间，使用语言种类,有感兴趣的看看，网址见describles (#1)
Assigned #1 to @falconhell.

**Comment by Sun-Kevin** [comment]
惊了，以为我博豪给我给配任务了😂

在 2017年3月6日，20:29，Atsukon Lee <notifications@github.com<mailto:notifications@github.com>> 写道：


Assigned #1<https://github.com/G-Club/G-Club-Master/issues/1> to @Sun-Kevin<https://github.com/Sun-Kevin>.

**Comment by Aisuko** [comment]
wakatime你绝对值得拥有😀


[image: --]

Aisuko Lee
[image: https://]about.me/aisuko
<https://about.me/aisuko?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=chrome_ext>



*Best regards / 诚挚的问候*
*Github: Aisuko*
*Organization:G-Club*

2017-03-07 9:15 GMT+08:00 falconhell <notifications@github.com>:

**Comment by yoyao** [comment]
真six，我都好久没上了。

**Comment by Aisuko** [comment]
闲聊到群里，这里使提问、解决问题的地方


[image: --]

Aisuko Lee
[image: https://]about.me/aisuko
<https://about.me/aisuko?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=chrome_ext>



*Best regards / 诚挚的问候*
*Github: Aisuko*
*Organization:G-Club*

2017-03-27 23:09 GMT+08:00 YoyaoFeng <notifications@github.com>:

**Comment by yoyao** [comment]
不要脸 放人家嘎克ki
